import java.util.*;
import javax.swing.*;
import java.awt.FlowLayout;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.*;
import java.io.*;
import javax.imageio.*;
import org.opencv.core.*;
import org.opencv.imgcodecs.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author johan
 */
public class GUI extends javax.swing.JFrame {
    String testPath;
    String trainPath;
    ImageData testImage;
    ArrayList<ImageData>[] trainImages;
    
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label2 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        lblChooseTest = new javax.swing.JLabel();
        btnBrowseTest = new javax.swing.JButton();
        lblPathTest = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBrowseTrain = new javax.swing.JButton();
        lblPathTrain = new javax.swing.JLabel();
        btnVerify = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        lblTestImage = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblResultWLIS = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblResultHMM = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblImageHMM = new javax.swing.JLabel();
        btnBrowseTestClass = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblTestClass = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        label2.setText("label2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Skripsi - NAT5102");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hand Signature Verification");

        lblChooseTest.setText("Choose test image path (file)");

        btnBrowseTest.setText("Browse...");
        btnBrowseTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBrowseTestMouseClicked(evt);
            }
        });
        btnBrowseTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseTestActionPerformed(evt);
            }
        });

        lblPathTest.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblPathTest.setText("(No path chosen)");
        lblPathTest.setMaximumSize(new java.awt.Dimension(240, 16));

        jLabel3.setText("Choose train images path (folder)");

        btnBrowseTrain.setText("Browse...");
        btnBrowseTrain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBrowseTrainMouseClicked(evt);
            }
        });

        lblPathTrain.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblPathTrain.setText("(No path chosen)");

        btnVerify.setText("Verify test image");
        btnVerify.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerifyMouseClicked(evt);
            }
        });
        btnVerify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel2.setText("Test image:");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel5.setText("Weighted Longest Increasing Subsequence");

        jLabel6.setText("Result:");

        jLabel4.setText("Hidden Markov Model");

        jLabel7.setText("Result:");

        jLabel9.setText("Most similar image:");

        btnBrowseTestClass.setText("Browse...");
        btnBrowseTestClass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBrowseTestClassMouseClicked(evt);
            }
        });
        btnBrowseTestClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseTestClassActionPerformed(evt);
            }
        });

        jLabel8.setText("Class:");

        jLabel10.setText("Choose related test image class");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVerify)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnBrowseTrain)
                        .addComponent(btnBrowseTest)
                        .addComponent(lblChooseTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                        .addComponent(lblPathTest, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPathTrain, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBrowseTestClass)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(lblTestImage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTestClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblResultWLIS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblResultHMM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblImageHMM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTestImage, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(lblTestClass, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblResultWLIS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(58, 58, 58)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(lblResultHMM, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblImageHMM, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblChooseTest)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBrowseTest)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPathTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBrowseTrain)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPathTrain)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBrowseTestClass)
                                .addGap(35, 35, 35)
                                .addComponent(btnVerify))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseTestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBrowseTestActionPerformed

    private void btnVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerifyActionPerformed

    private void btnBrowseTestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBrowseTestMouseClicked
        JFileChooser fc = new JFileChooser("C:\\_My Files\\Johan\\GitHub\\Skripsi-NAT5102\\Dataset");
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int returnVal = fc.showOpenDialog(this);
        
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File testFile = fc.getSelectedFile();
            testPath = testFile.getAbsolutePath();
            testImage = new ImageData(testPath, false, -1);
            
            BufferedImage bi = null;
            try {
                bi = ImageIO.read(new File(testPath));
            } catch (IOException e) {
                e.printStackTrace();
            }
            
            Image img = bi.getScaledInstance(lblTestImage.getWidth(), lblTestImage.getHeight(), Image.SCALE_SMOOTH);
            
            lblPathTest.setText(testPath);
            lblPathTest.setToolTipText(testPath);
            lblTestImage.setIcon(new ImageIcon(img));
        } else {
            System.out.println("Cancelled by user.");
        }
    }//GEN-LAST:event_btnBrowseTestMouseClicked

    private void btnBrowseTrainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBrowseTrainMouseClicked
        JFileChooser fc = new JFileChooser("C:\\_My Files\\Johan\\GitHub\\Skripsi-NAT5102\\Dataset");
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = fc.showOpenDialog(this);
        
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File trainFolder = fc.getSelectedFile();
            trainPath = trainFolder.getAbsolutePath();
            FolderProcessor fp = new FolderProcessor(trainPath);
            trainImages = convertPathsToImageData(fp.getFilePaths(), true);
            
            lblPathTrain.setText(trainPath);
            lblPathTrain.setToolTipText(trainPath);
        } else {
            System.out.println("Cancelled by user.");
        }
    }//GEN-LAST:event_btnBrowseTrainMouseClicked

    private void btnVerifyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerifyMouseClicked
        ImageProcessor ip = new ImageProcessor();
        testImage.detectKeypoints(200);
        
        ArrayList<ArrayList<MatOfDMatch>> matches = ip.matchKeypoints(testImage, trainImages, 20);
        
        // WLIS
        WLISValidator wlis = new WLISValidator(trainImages, testImage, matches);
        wlis.validateImage();
    }//GEN-LAST:event_btnVerifyMouseClicked

    private void btnBrowseTestClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseTestClassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBrowseTestClassActionPerformed

    private void btnBrowseTestClassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBrowseTestClassMouseClicked
        JFileChooser fc = new JFileChooser(trainPath);
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = fc.showOpenDialog(this);
        
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File classFolder = fc.getSelectedFile();
            String classPath = classFolder.getAbsolutePath();
            int testClass = -1;
            
            for (int i = 0; i < trainImages.length; i++) {
                System.out.println(trainImages[i].get(0).getClassPath());
                if (classPath.equals(trainImages[i].get(0).getClassPath())) {
                    testClass = i;
                    lblTestClass.setText(trainImages[i].get(0).getClassPath());
                    break;
                }
            }
            
            testImage.setIndex(testClass);
        } else {
            System.out.println("Cancelled by user.");
        }
    }//GEN-LAST:event_btnBrowseTestClassMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUI gui = new GUI();
                gui.setVisible(true);
                gui.setLocationRelativeTo(null);
            }
        });
    }
    
    public static ArrayList<ImageData>[] convertPathsToImageData(ArrayList<String>[] paths, boolean imageType) {
        ArrayList<ImageData>[] res = new ArrayList[paths.length];
        for (int i = 0; i < paths.length; i++) {
            res[i] = new ArrayList<>();
        }
        
        for (int i = 0; i < paths.length; i++) {
            if (paths[i] != null) {
                for (int j = 0; j < paths[i].size(); j++) {
                    ImageData id = new ImageData(paths[i].get(j), imageType, i);
                    id.detectKeypoints(400);
                    res[i].add(id);
                }
            }
        }
        
        return res;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowseTest;
    private javax.swing.JButton btnBrowseTestClass;
    private javax.swing.JButton btnBrowseTrain;
    private javax.swing.JButton btnVerify;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private java.awt.Label label2;
    private javax.swing.JLabel lblChooseTest;
    private javax.swing.JLabel lblImageHMM;
    private javax.swing.JLabel lblPathTest;
    private javax.swing.JLabel lblPathTrain;
    private javax.swing.JLabel lblResultHMM;
    private javax.swing.JLabel lblResultWLIS;
    private javax.swing.JLabel lblTestClass;
    private javax.swing.JLabel lblTestImage;
    // End of variables declaration//GEN-END:variables
}
